/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.criminals.view;

import com.criminals.model.criminalmodel;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class AdminHomepage extends javax.swing.JFrame {
    ArrayList<criminalmodel> Criminal = new ArrayList<criminalmodel>();
    
    private DefaultTableModel tableModel;
    /**
     * Creates new form AdminHomepage
     */
    public AdminHomepage() {
        initComponents();
        addInitialCriminalInformation();
        tableModel = (DefaultTableModel) tblAdminInCustody.getModel();
    }
    
    private void addInitialCriminalInformation(){
        criminalmodel Criminal1 = new criminalmodel(01,"Sean Combs","Racketeering Conspiracy","Life in Prision");
        criminalmodel Criminal2 = new criminalmodel(02,"Patrick Wood Crusius","Perpetrator of the El Paso Shooting","90 consecutive life sentences without parole");
        criminalmodel Criminal3 = new criminalmodel(03,"Terry Nichols","161 counts of first degree murder","162 life sentences");
        criminalmodel Criminal4 = new criminalmodel(04,"Bowers Robert","Mass shooting","Death sentence");
        criminalmodel Criminal5 = new criminalmodel(05,"Barry Walker","Serial Rapist","39 life sentences plus 1.719 years without parole");
        
        Criminal.add(Criminal1);
        addDataToTable(Criminal1);
        
        Criminal.add(Criminal2);
        addDataToTable(Criminal2);
        
        Criminal.add(Criminal3);
        addDataToTable(Criminal3);
        
        Criminal.add(Criminal4);
        addDataToTable(Criminal4);
        
        Criminal.add(Criminal5);
        addDataToTable(Criminal5);
    }
    
    private void addDataToTable(criminalmodel student)
    {
        tableModel = (DefaultTableModel) tblAdminInCustody.getModel();
        tableModel.addRow(new Object[]{student.getId(), student.getName(), student.getCrime(), student.getSentence()});
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlAdminPage = new javax.swing.JPanel();
        lblIcon = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        lblSearch = new javax.swing.JLabel();
        btnLogOut = new javax.swing.JButton();
        tpaneAdminpage = new javax.swing.JTabbedPane();
        pnlAdminHome = new javax.swing.JPanel();
        lblBackgrounImg = new javax.swing.JLabel();
        pnlHomeinfo = new javax.swing.JPanel();
        lblHelpFind = new javax.swing.JLabel();
        lblGetRapSheet = new javax.swing.JLabel();
        lblLearn = new javax.swing.JLabel();
        lblLeaveATip = new javax.swing.JLabel();
        lblCrimeStats = new javax.swing.JLabel();
        lblRespondACrime = new javax.swing.JLabel();
        pnlAdminMWanted = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        pnlAdminInCustody = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblAdminInCustody = new javax.swing.JTable();
        txtFieldId = new javax.swing.JTextField();
        txtFieldName = new javax.swing.JTextField();
        txtFieldCrime = new javax.swing.JTextField();
        txtFieldSentence = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnRemove = new javax.swing.JButton();
        pnlAdminHelp = new javax.swing.JPanel();
        pnlAdminContact = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlAdminPage.setBackground(new java.awt.Color(255, 255, 204));

        lblIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/criminals/view/logo.png"))); // NOI18N

        lblTitle.setFont(new java.awt.Font("Sitka Heading", 0, 36)); // NOI18N
        lblTitle.setText("Criminal Log");

        lblSearch.setText("Search");

        btnLogOut.setText("LogOut");
        btnLogOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogOutActionPerformed(evt);
            }
        });

        pnlAdminHome.setBackground(new java.awt.Color(255, 255, 204));

        lblBackgrounImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/criminals/view/11.jpg"))); // NOI18N

        pnlHomeinfo.setBackground(new java.awt.Color(255, 255, 255));

        lblHelpFind.setFont(new java.awt.Font("Segoe UI Emoji", 0, 24)); // NOI18N
        lblHelpFind.setText("Help Find Fugitives");

        lblGetRapSheet.setFont(new java.awt.Font("Segoe UI Emoji", 0, 24)); // NOI18N
        lblGetRapSheet.setText("Get a Rap sheet(Identity History)");

        lblLearn.setFont(new java.awt.Font("Segoe UI Emoji", 0, 24)); // NOI18N
        lblLearn.setText("Learn about crimes and scams");

        lblLeaveATip.setFont(new java.awt.Font("Segoe UI Emoji", 0, 24)); // NOI18N
        lblLeaveATip.setText("Leave a Tip");

        lblCrimeStats.setFont(new java.awt.Font("Segoe UI Emoji", 0, 24)); // NOI18N
        lblCrimeStats.setText("Find Crime Stats");

        lblRespondACrime.setFont(new java.awt.Font("Segoe UI Emoji", 0, 24)); // NOI18N
        lblRespondACrime.setText("Learn to respond to a crime");

        javax.swing.GroupLayout pnlHomeinfoLayout = new javax.swing.GroupLayout(pnlHomeinfo);
        pnlHomeinfo.setLayout(pnlHomeinfoLayout);
        pnlHomeinfoLayout.setHorizontalGroup(
            pnlHomeinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHomeinfoLayout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addGroup(pnlHomeinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLeaveATip, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHelpFind, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(367, 367, 367)
                .addGroup(pnlHomeinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCrimeStats, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblGetRapSheet, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlHomeinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblRespondACrime)
                    .addComponent(lblLearn))
                .addGap(35, 35, 35))
        );
        pnlHomeinfoLayout.setVerticalGroup(
            pnlHomeinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHomeinfoLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(pnlHomeinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHelpFind)
                    .addComponent(lblGetRapSheet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblLearn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(73, 73, 73)
                .addGroup(pnlHomeinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLeaveATip)
                    .addComponent(lblCrimeStats, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblRespondACrime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        javax.swing.GroupLayout pnlAdminHomeLayout = new javax.swing.GroupLayout(pnlAdminHome);
        pnlAdminHome.setLayout(pnlAdminHomeLayout);
        pnlAdminHomeLayout.setHorizontalGroup(
            pnlAdminHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAdminHomeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAdminHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlHomeinfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblBackgrounImg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlAdminHomeLayout.setVerticalGroup(
            pnlAdminHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAdminHomeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlHomeinfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblBackgrounImg, javax.swing.GroupLayout.PREFERRED_SIZE, 306, Short.MAX_VALUE))
        );

        tpaneAdminpage.addTab("Home", pnlAdminHome);

        pnlAdminMWanted.setBackground(new java.awt.Color(255, 255, 204));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout pnlAdminMWantedLayout = new javax.swing.GroupLayout(pnlAdminMWanted);
        pnlAdminMWanted.setLayout(pnlAdminMWantedLayout);
        pnlAdminMWantedLayout.setHorizontalGroup(
            pnlAdminMWantedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1612, Short.MAX_VALUE)
        );
        pnlAdminMWantedLayout.setVerticalGroup(
            pnlAdminMWantedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 473, Short.MAX_VALUE)
        );

        tpaneAdminpage.addTab("Most Wanted", pnlAdminMWanted);

        pnlAdminInCustody.setBackground(new java.awt.Color(255, 255, 204));

        tblAdminInCustody.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Criminal Id", "Criminal Name", "Crime Comitted", "Sentence"
            }
        ));
        tblAdminInCustody.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblAdminInCustodyMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblAdminInCustody);

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnRemove.setText("Remove");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlAdminInCustodyLayout = new javax.swing.GroupLayout(pnlAdminInCustody);
        pnlAdminInCustody.setLayout(pnlAdminInCustodyLayout);
        pnlAdminInCustodyLayout.setHorizontalGroup(
            pnlAdminInCustodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAdminInCustodyLayout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(txtFieldId, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(185, 185, 185)
                .addComponent(txtFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 346, Short.MAX_VALUE)
                .addGroup(pnlAdminInCustodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAdminInCustodyLayout.createSequentialGroup()
                        .addComponent(btnAdd)
                        .addGap(140, 140, 140)
                        .addComponent(btnRemove))
                    .addComponent(txtFieldCrime, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pnlAdminInCustodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAdminInCustodyLayout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(btnUpdate))
                    .addGroup(pnlAdminInCustodyLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(txtFieldSentence, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(100, 100, 100))
        );
        pnlAdminInCustodyLayout.setVerticalGroup(
            pnlAdminInCustodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAdminInCustodyLayout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlAdminInCustodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtFieldName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlAdminInCustodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtFieldId, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtFieldSentence, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtFieldCrime, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(pnlAdminInCustodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdate)
                    .addComponent(btnAdd)
                    .addComponent(btnRemove))
                .addGap(27, 27, 27))
        );

        tpaneAdminpage.addTab("In-Custody", pnlAdminInCustody);

        pnlAdminHelp.setBackground(new java.awt.Color(255, 255, 204));

        javax.swing.GroupLayout pnlAdminHelpLayout = new javax.swing.GroupLayout(pnlAdminHelp);
        pnlAdminHelp.setLayout(pnlAdminHelpLayout);
        pnlAdminHelpLayout.setHorizontalGroup(
            pnlAdminHelpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1612, Short.MAX_VALUE)
        );
        pnlAdminHelpLayout.setVerticalGroup(
            pnlAdminHelpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 473, Short.MAX_VALUE)
        );

        tpaneAdminpage.addTab("Help", pnlAdminHelp);

        pnlAdminContact.setBackground(new java.awt.Color(255, 255, 204));

        javax.swing.GroupLayout pnlAdminContactLayout = new javax.swing.GroupLayout(pnlAdminContact);
        pnlAdminContact.setLayout(pnlAdminContactLayout);
        pnlAdminContactLayout.setHorizontalGroup(
            pnlAdminContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1612, Short.MAX_VALUE)
        );
        pnlAdminContactLayout.setVerticalGroup(
            pnlAdminContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 473, Short.MAX_VALUE)
        );

        tpaneAdminpage.addTab("Contact Us", pnlAdminContact);

        javax.swing.GroupLayout pnlAdminPageLayout = new javax.swing.GroupLayout(pnlAdminPage);
        pnlAdminPage.setLayout(pnlAdminPageLayout);
        pnlAdminPageLayout.setHorizontalGroup(
            pnlAdminPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAdminPageLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAdminPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAdminPageLayout.createSequentialGroup()
                        .addComponent(lblIcon)
                        .addGap(18, 18, 18)
                        .addComponent(lblTitle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLogOut))
                    .addComponent(tpaneAdminpage)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAdminPageLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lblSearch)))
                .addContainerGap())
        );
        pnlAdminPageLayout.setVerticalGroup(
            pnlAdminPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAdminPageLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAdminPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIcon)
                    .addGroup(pnlAdminPageLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(pnlAdminPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTitle)
                            .addComponent(btnLogOut))))
                .addGap(18, 18, 18)
                .addComponent(lblSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tpaneAdminpage, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlAdminPage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlAdminPage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLogOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogOutActionPerformed
        // TODO add your handling code here:
        HomePage HP = new HomePage();
        HP.show();
        dispose();
    }//GEN-LAST:event_btnLogOutActionPerformed

    private void tblAdminInCustodyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblAdminInCustodyMouseClicked
        // TODO add your handling code here:
        //Set data to the respective TExtfields
        
        DefaultTableModel tblModel = (DefaultTableModel)tblAdminInCustody.getModel();
        // set data to text field when row is selected.
        String tblId = tblModel.getValueAt(tblAdminInCustody.getSelectedRow(),0).toString();
        String tblName = tblModel.getValueAt(tblAdminInCustody.getSelectedRow(),1).toString();
        String tblCrime = tblModel.getValueAt(tblAdminInCustody.getSelectedRow(),2).toString();
        String tblSentence = tblModel.getValueAt(tblAdminInCustody.getSelectedRow(),3).toString();
        
        //set to the textfield
        txtFieldId.setText(tblId);
        txtFieldName.setText(tblName);
        txtFieldCrime.setText(tblCrime);
        txtFieldSentence.setText(tblSentence);
        
    }//GEN-LAST:event_tblAdminInCustodyMouseClicked

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        //get table model
        DefaultTableModel tblModel = (DefaultTableModel)tblAdminInCustody.getModel();
        if(tblAdminInCustody.getSelectedRowCount() == 1){
            // update if single row is selected
            String id = txtFieldId.getText();
            String name = txtFieldName.getText();
            String crime = txtFieldCrime.getText();
            String sentence = txtFieldSentence.getText();
            
            //set updated value on table
            
            tblModel.setValueAt(id,tblAdminInCustody.getSelectedRow(), 0);
            tblModel.setValueAt(name,tblAdminInCustody.getSelectedRow(), 1);
            tblModel.setValueAt(crime,tblAdminInCustody.getSelectedRow(), 2);
            tblModel.setValueAt(sentence,tblAdminInCustody.getSelectedRow(), 3);
            
            //Display Update Message
            JOptionPane.showMessageDialog(this,"updated sucessfully.");
            
        }
        else{
            if (tblAdminInCustody.getRowCount() == 0){
                JOptionPane.showMessageDialog(this, "doit properly.");
            }
            else{
                JOptionPane.showMessageDialog(this, "doit properly please....");
            }
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        /*
        no conditions.
        int Id = Integer.parseInt(txtFieldId.getText());
        String Name = txtFieldName.getText();
        String Crime = txtFieldCrime.getText();
        String Sentence = txtFieldSentence.getText();

        criminalmodel studentinfo = new criminalmodel(Id,Name,Crime,Sentence);
        Criminal.add(studentinfo);
        addDataToTable(studentinfo);
        */
        if(txtFieldId.getText().isEmpty() || txtFieldName.getText().isEmpty()|| txtFieldCrime.getText().isEmpty() || txtFieldSentence.getText().isEmpty()){
            JOptionPane.showMessageDialog(rootPane,"Please fill out all the information","Alert",JOptionPane.WARNING_MESSAGE);
            return;
            }
            
            try{
                int Id = Integer.parseInt(txtFieldId.getText());
                String Name = txtFieldName.getText();
                String Crime = txtFieldCrime.getText();
                String Sentence = txtFieldSentence.getText();
                tableModel = (DefaultTableModel) tblAdminInCustody.getModel();
                Boolean IN = false;
                for(criminalmodel objcriminalmodel: Criminal){
                   if(objcriminalmodel.getId() == Integer.parseInt(txtFieldId.getText())){
                       IN = true;
                    }   
                }
                if(IN == false){
                    criminalmodel studentinfo = new criminalmodel(Id,Name,Crime,Sentence);
                        Criminal.add(studentinfo);
                        addDataToTable(studentinfo);
                }else{
                       JOptionPane.showMessageDialog(this,"same id.","Information",JOptionPane.INFORMATION_MESSAGE);
                   }
                
                
                }
            catch(NumberFormatException e1){
                JOptionPane.showMessageDialog(rootPane,"Criminal Id should be a number","Alert",JOptionPane.WARNING_MESSAGE);
                }
        
    
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        // TODO add your handling code here:
       
        try 
        {
            boolean Remove = false;
            /*
            for(criminalmodel objcriminalmodel: Criminal)
            {
                if(objcriminalmodel.getId()==Integer.parseInt(txtFieldId.getText()))
                {
                    Remove = true;
                    Criminal.remove(objcriminalmodel);
                    JOptionPane.showMessageDialog(this,"Criminal has been removed.","Information",JOptionPane.INFORMATION_MESSAGE);
                }
            }*/
            /*
            Iterator<criminalmodel> itr = Criminal.iterator();
            while(itr.hasNext()){
                criminalmodel objcriminalmodel = itr.next();
                if(objcriminalmodel.getId() == Integer.parseInt(txtFieldId.getText())){
                    Remove = true;
                    itr.remove();
                    JOptionPane.showMessageDialog(this,"Criminal has been removed.","Information",JOptionPane.INFORMATION_MESSAGE);
                    tableModel = (DefaultTableModel) tblAdminInCustody.getModel();
                    int rowCount = tblAdminInCustody.getRowCount();
                    for (int i = 0; i < rowCount; i++){
                        
                        tableModel.removeRow(i);
                        break;
                    }
                }
*/           
                Iterator<criminalmodel> itr = Criminal.iterator();
                while(itr.hasNext()){
                    criminalmodel objcriminalmodel = itr.next();
                    if(objcriminalmodel.getId() == Integer.parseInt(txtFieldId.getText())){
                        Remove = true;
                        itr.remove();
                        JOptionPane.showMessageDialog(this,"Criminal has been removed.","Information",JOptionPane.INFORMATION_MESSAGE);
                        tableModel = (DefaultTableModel) tblAdminInCustody.getModel();
                        int rowCount = tblAdminInCustody.getRowCount();
                        for (int i = 0; i < rowCount; i++){
                             if (tableModel.getValueAt(i, 0).equals(Integer.parseInt(txtFieldId.getText()))) {
                            tableModel.removeRow(i);
                            break; // Exit loop after removing the row
                        }
                            
                        }
                    }
            }

            if(Remove == false)
            {
                JOptionPane.showMessageDialog(this,"Criminal is not in custody.","Warning",JOptionPane.WARNING_MESSAGE);
                return;
            }
        } 
        catch (NumberFormatException e9) 
        {
            JOptionPane.showMessageDialog(this,"Wrong data type.","Warning",JOptionPane.WARNING_MESSAGE);
        }
        
    }//GEN-LAST:event_btnRemoveActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminHomepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminHomepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminHomepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminHomepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminHomepage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnLogOut;
    private javax.swing.JButton btnRemove;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lblBackgrounImg;
    private javax.swing.JLabel lblCrimeStats;
    private javax.swing.JLabel lblGetRapSheet;
    private javax.swing.JLabel lblHelpFind;
    private javax.swing.JLabel lblIcon;
    private javax.swing.JLabel lblLearn;
    private javax.swing.JLabel lblLeaveATip;
    private javax.swing.JLabel lblRespondACrime;
    private javax.swing.JLabel lblSearch;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel pnlAdminContact;
    private javax.swing.JPanel pnlAdminHelp;
    private javax.swing.JPanel pnlAdminHome;
    private javax.swing.JPanel pnlAdminInCustody;
    private javax.swing.JPanel pnlAdminMWanted;
    private javax.swing.JPanel pnlAdminPage;
    private javax.swing.JPanel pnlHomeinfo;
    private javax.swing.JTable tblAdminInCustody;
    private javax.swing.JTabbedPane tpaneAdminpage;
    private javax.swing.JTextField txtFieldCrime;
    private javax.swing.JTextField txtFieldId;
    private javax.swing.JTextField txtFieldName;
    private javax.swing.JTextField txtFieldSentence;
    // End of variables declaration//GEN-END:variables

    
}
