/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.criminals.view;

import com.criminals.controller.Algorithm.InsertionSort;
import com.criminals.controller.Algorithm.MergeSort;
import com.criminals.controller.Algorithm.SelectionSort;
import com.criminals.model.MostWantedModel;
import com.criminals.model.CriminalModel;
import java.awt.event.ActionListener;
import java.util.ArrayList;
import java.util.Iterator;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Shuva Nath Shrestha 23048621
 */
public class AdminHomepage extends javax.swing.JFrame {

    ArrayList<CriminalModel> Criminal = new ArrayList<CriminalModel>();
    ArrayList<MostWantedModel> MostWanted = new ArrayList<MostWantedModel>();

    private DefaultTableModel tableModel;
    private DefaultTableModel tableModel1;

    /**
     * Creates new form AdminHomepage
     */
    public AdminHomepage() {
        initComponents();
        addInitialCriminalInformation();
        addWantedCriminalInformation();
        tableModel = (DefaultTableModel) tblAdminInCustody.getModel();
        tableModel1 = (DefaultTableModel) tblMostWanted.getModel();
    }

    private void addInitialCriminalInformation() {
        CriminalModel Criminal1 = new CriminalModel(01, "Sean Combs", "Racketeering Conspiracy", "Life in Prision");
        CriminalModel Criminal2 = new CriminalModel(02, "Patrick Wood Crusius", "Perpetrator of the El Paso Shooting", "90 consecutive life sentences without parole");
        CriminalModel Criminal3 = new CriminalModel(03, "Terry Nichols", "161 counts of first degree murder", "162 life sentences");
        CriminalModel Criminal4 = new CriminalModel(04, "Bowers Robert", "Mass shooting", "Death sentence");
        CriminalModel Criminal5 = new CriminalModel(05, "Barry Walker", "Serial Rapist", "39 life sentences plus 1.719 years without parole");

        Criminal.add(Criminal1);
        addDataToTable(Criminal1);

        Criminal.add(Criminal2);
        addDataToTable(Criminal2);

        Criminal.add(Criminal3);
        addDataToTable(Criminal3);

        Criminal.add(Criminal4);
        addDataToTable(Criminal4);

        Criminal.add(Criminal5);
        addDataToTable(Criminal5);
    }

    private void addWantedCriminalInformation() {
        MostWantedModel Criminal1 = new MostWantedModel(01, "Sean Combs", "Racketeering Conspiracy", 500);
        MostWantedModel Criminal2 = new MostWantedModel(02, "Patrick Wood Crusius", "Perpetrator of the El Paso Shooting", 521);
        MostWantedModel Criminal3 = new MostWantedModel(03, "Terry Nichols", "161 counts of first degree murder", 623);
        MostWantedModel Criminal4 = new MostWantedModel(04, "Bowers Robert", "Mass shooting", 784);
        MostWantedModel Criminal5 = new MostWantedModel(05, "Barry Walker", "Serial Rapist", 896);

        MostWanted.add(Criminal1);
        addDataToTable1(Criminal1);

        MostWanted.add(Criminal2);
        addDataToTable1(Criminal2);

        MostWanted.add(Criminal3);
        addDataToTable1(Criminal3);

        MostWanted.add(Criminal4);
        addDataToTable1(Criminal4);

        MostWanted.add(Criminal5);
        addDataToTable1(Criminal5);
    }

    private void addDataToTable(CriminalModel criminal) {
        tableModel = (DefaultTableModel) tblAdminInCustody.getModel();
        tableModel.addRow(new Object[]{criminal.getId(), criminal.getName(), criminal.getCrime(), criminal.getSentence()});
    }

    private void addDataToTable1(MostWantedModel criminal) {
        tableModel1 = (DefaultTableModel) tblMostWanted.getModel();
        tableModel1.addRow(new Object[]{criminal.getId(), criminal.getName(), criminal.getCrime(), criminal.getBounty()});
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlAdminPage = new javax.swing.JPanel();
        lblIcon = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        tpaneAdminPage = new javax.swing.JTabbedPane();
        pnlAdminHome = new javax.swing.JPanel();
        lblBackgrounImg = new javax.swing.JLabel();
        pnlHomeinfo = new javax.swing.JPanel();
        lblHelpFind = new javax.swing.JLabel();
        lblGetRapSheet = new javax.swing.JLabel();
        lblLearn = new javax.swing.JLabel();
        lblLeaveATip = new javax.swing.JLabel();
        lblCrimeStats = new javax.swing.JLabel();
        lblRespondACrime = new javax.swing.JLabel();
        pnlAdminMWanted = new javax.swing.JPanel();
        scrlPaneMostWanted = new javax.swing.JScrollPane();
        tblMostWanted = new javax.swing.JTable();
        cmbBxSorting = new javax.swing.JComboBox<>();
        pnlAdminInCustody = new javax.swing.JPanel();
        scrlPaneInCustody = new javax.swing.JScrollPane();
        tblAdminInCustody = new javax.swing.JTable();
        txtFldId = new javax.swing.JTextField();
        txtFldName = new javax.swing.JTextField();
        txtFldCrime = new javax.swing.JTextField();
        txtFldSentence = new javax.swing.JTextField();
        btnUpdate = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnRemove = new javax.swing.JButton();
        cmbBxSort = new javax.swing.JComboBox<>();
        pnlAdminHelp = new javax.swing.JPanel();
        lblHelpWithWebsite = new javax.swing.JLabel();
        lblIssue = new javax.swing.JLabel();
        pnlAdminContact = new javax.swing.JPanel();
        lblQuerriesTitle = new javax.swing.JLabel();
        txtFldQueries = new javax.swing.JTextField();
        btnSend = new javax.swing.JButton();
        btnSearch = new javax.swing.JButton();
        txtFldSearch = new javax.swing.JTextField();
        btnLogin = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pnlAdminPage.setBackground(new java.awt.Color(255, 255, 204));

        lblIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/criminals/resources/logo.png"))); // NOI18N

        lblTitle.setFont(new java.awt.Font("Sitka Heading", 0, 36)); // NOI18N
        lblTitle.setText("Criminal Log");

        pnlAdminHome.setBackground(new java.awt.Color(255, 255, 204));

        lblBackgrounImg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/criminals/resources/HomeScreenPicture.jpg"))); // NOI18N

        pnlHomeinfo.setBackground(new java.awt.Color(255, 255, 255));

        lblHelpFind.setFont(new java.awt.Font("Segoe UI Emoji", 0, 24)); // NOI18N
        lblHelpFind.setText("Help Find Fugitives");

        lblGetRapSheet.setFont(new java.awt.Font("Segoe UI Emoji", 0, 24)); // NOI18N
        lblGetRapSheet.setText("Get a Rap sheet(Identity History)");

        lblLearn.setFont(new java.awt.Font("Segoe UI Emoji", 0, 24)); // NOI18N
        lblLearn.setText("Learn about crimes and scams");

        lblLeaveATip.setFont(new java.awt.Font("Segoe UI Emoji", 0, 24)); // NOI18N
        lblLeaveATip.setText("Leave a Tip");

        lblCrimeStats.setFont(new java.awt.Font("Segoe UI Emoji", 0, 24)); // NOI18N
        lblCrimeStats.setText("Find Crime Stats");

        lblRespondACrime.setFont(new java.awt.Font("Segoe UI Emoji", 0, 24)); // NOI18N
        lblRespondACrime.setText("Learn to respond to a crime");

        javax.swing.GroupLayout pnlHomeinfoLayout = new javax.swing.GroupLayout(pnlHomeinfo);
        pnlHomeinfo.setLayout(pnlHomeinfoLayout);
        pnlHomeinfoLayout.setHorizontalGroup(
            pnlHomeinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHomeinfoLayout.createSequentialGroup()
                .addGap(118, 118, 118)
                .addGroup(pnlHomeinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblLeaveATip, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblHelpFind, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(367, 367, 367)
                .addGroup(pnlHomeinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblCrimeStats, javax.swing.GroupLayout.PREFERRED_SIZE, 301, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblGetRapSheet, javax.swing.GroupLayout.PREFERRED_SIZE, 374, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pnlHomeinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblRespondACrime)
                    .addComponent(lblLearn))
                .addGap(35, 35, 35))
        );
        pnlHomeinfoLayout.setVerticalGroup(
            pnlHomeinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHomeinfoLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(pnlHomeinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHelpFind)
                    .addComponent(lblGetRapSheet, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblLearn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(14, 14, 14)
                .addGroup(pnlHomeinfoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLeaveATip)
                    .addComponent(lblCrimeStats)
                    .addComponent(lblRespondACrime, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlAdminHomeLayout = new javax.swing.GroupLayout(pnlAdminHome);
        pnlAdminHome.setLayout(pnlAdminHomeLayout);
        pnlAdminHomeLayout.setHorizontalGroup(
            pnlAdminHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAdminHomeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAdminHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(pnlHomeinfo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblBackgrounImg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlAdminHomeLayout.setVerticalGroup(
            pnlAdminHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAdminHomeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlHomeinfo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblBackgrounImg, javax.swing.GroupLayout.PREFERRED_SIZE, 365, Short.MAX_VALUE))
        );

        tpaneAdminPage.addTab("Home", pnlAdminHome);

        pnlAdminMWanted.setBackground(new java.awt.Color(255, 255, 204));

        tblMostWanted.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id", "Name", "Crime", "Bounty"
            }
        ));
        scrlPaneMostWanted.setViewportView(tblMostWanted);

        cmbBxSorting.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sort by Id", "Sort by Name", "Sort by Bounty" }));
        cmbBxSorting.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbBxSortingActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlAdminMWantedLayout = new javax.swing.GroupLayout(pnlAdminMWanted);
        pnlAdminMWanted.setLayout(pnlAdminMWantedLayout);
        pnlAdminMWantedLayout.setHorizontalGroup(
            pnlAdminMWantedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrlPaneMostWanted, javax.swing.GroupLayout.DEFAULT_SIZE, 1612, Short.MAX_VALUE)
            .addGroup(pnlAdminMWantedLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(cmbBxSorting, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        pnlAdminMWantedLayout.setVerticalGroup(
            pnlAdminMWantedLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAdminMWantedLayout.createSequentialGroup()
                .addComponent(scrlPaneMostWanted, javax.swing.GroupLayout.PREFERRED_SIZE, 402, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(cmbBxSorting, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 31, Short.MAX_VALUE))
        );

        tpaneAdminPage.addTab("Most Wanted", pnlAdminMWanted);

        pnlAdminInCustody.setBackground(new java.awt.Color(255, 255, 204));

        tblAdminInCustody.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Criminal Id", "Criminal Name", "Crime Comitted", "Sentence"
            }
        ));
        tblAdminInCustody.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblAdminInCustodyMouseClicked(evt);
            }
        });
        scrlPaneInCustody.setViewportView(tblAdminInCustody);

        txtFldName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFldNameActionPerformed(evt);
            }
        });

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });

        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnRemove.setText("Remove");
        btnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRemoveActionPerformed(evt);
            }
        });

        cmbBxSort.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sort by Id", "Sort by Names" }));
        cmbBxSort.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbBxSortActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlAdminInCustodyLayout = new javax.swing.GroupLayout(pnlAdminInCustody);
        pnlAdminInCustody.setLayout(pnlAdminInCustodyLayout);
        pnlAdminInCustodyLayout.setHorizontalGroup(
            pnlAdminInCustodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scrlPaneInCustody)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAdminInCustodyLayout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(txtFldId, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(185, 185, 185)
                .addComponent(txtFldName, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 346, Short.MAX_VALUE)
                .addGroup(pnlAdminInCustodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAdminInCustodyLayout.createSequentialGroup()
                        .addComponent(btnAdd)
                        .addGap(140, 140, 140)
                        .addComponent(btnRemove))
                    .addComponent(txtFldCrime, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(pnlAdminInCustodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnlAdminInCustodyLayout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(txtFldSentence, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(100, 100, 100))
                    .addGroup(pnlAdminInCustodyLayout.createSequentialGroup()
                        .addGap(124, 124, 124)
                        .addComponent(btnUpdate)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cmbBxSort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        pnlAdminInCustodyLayout.setVerticalGroup(
            pnlAdminInCustodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAdminInCustodyLayout.createSequentialGroup()
                .addComponent(scrlPaneInCustody, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlAdminInCustodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtFldName, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(pnlAdminInCustodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtFldId, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtFldSentence, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtFldCrime, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                .addGroup(pnlAdminInCustodyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnUpdate)
                    .addComponent(btnAdd)
                    .addComponent(btnRemove)
                    .addComponent(cmbBxSort, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27))
        );

        tpaneAdminPage.addTab("In-Custody", pnlAdminInCustody);

        pnlAdminHelp.setBackground(new java.awt.Color(255, 255, 204));

        lblHelpWithWebsite.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblHelpWithWebsite.setText("Need help with the website? Click here.");

        lblIssue.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblIssue.setText("Found an issue with the website? Click here.");

        javax.swing.GroupLayout pnlAdminHelpLayout = new javax.swing.GroupLayout(pnlAdminHelp);
        pnlAdminHelp.setLayout(pnlAdminHelpLayout);
        pnlAdminHelpLayout.setHorizontalGroup(
            pnlAdminHelpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAdminHelpLayout.createSequentialGroup()
                .addGroup(pnlAdminHelpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblIssue, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlAdminHelpLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lblHelpWithWebsite, javax.swing.GroupLayout.PREFERRED_SIZE, 638, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(917, Short.MAX_VALUE))
        );
        pnlAdminHelpLayout.setVerticalGroup(
            pnlAdminHelpLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAdminHelpLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblHelpWithWebsite, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblIssue, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(181, Short.MAX_VALUE))
        );

        tpaneAdminPage.addTab("Help", pnlAdminHelp);

        pnlAdminContact.setBackground(new java.awt.Color(255, 255, 204));

        lblQuerriesTitle.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblQuerriesTitle.setText("Send us your queries here.");

        txtFldQueries.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtFldQueriesActionPerformed(evt);
            }
        });

        btnSend.setText("send");
        btnSend.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlAdminContactLayout = new javax.swing.GroupLayout(pnlAdminContact);
        pnlAdminContact.setLayout(pnlAdminContactLayout);
        pnlAdminContactLayout.setHorizontalGroup(
            pnlAdminContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAdminContactLayout.createSequentialGroup()
                .addGap(523, 523, 523)
                .addComponent(lblQuerriesTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 474, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(615, Short.MAX_VALUE))
            .addGroup(pnlAdminContactLayout.createSequentialGroup()
                .addGroup(pnlAdminContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtFldQueries)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAdminContactLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnSend)))
                .addContainerGap())
        );
        pnlAdminContactLayout.setVerticalGroup(
            pnlAdminContactLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAdminContactLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblQuerriesTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtFldQueries, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSend)
                .addContainerGap(75, Short.MAX_VALUE))
        );

        tpaneAdminPage.addTab("Contact Us", pnlAdminContact);

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        txtFldSearch.setText("Search here");

        btnLogin.setText("Log out");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlAdminPageLayout = new javax.swing.GroupLayout(pnlAdminPage);
        pnlAdminPage.setLayout(pnlAdminPageLayout);
        pnlAdminPageLayout.setHorizontalGroup(
            pnlAdminPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAdminPageLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAdminPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAdminPageLayout.createSequentialGroup()
                        .addComponent(lblIcon)
                        .addGap(18, 18, 18)
                        .addComponent(lblTitle)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLogin)
                        .addGap(14, 14, 14))
                    .addComponent(tpaneAdminPage)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAdminPageLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(txtFldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSearch)))
                .addContainerGap())
        );
        pnlAdminPageLayout.setVerticalGroup(
            pnlAdminPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAdminPageLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlAdminPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnlAdminPageLayout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(pnlAdminPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblTitle)
                            .addComponent(btnLogin)))
                    .addComponent(lblIcon))
                .addGap(18, 18, 18)
                .addGroup(pnlAdminPageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSearch)
                    .addComponent(txtFldSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(tpaneAdminPage, javax.swing.GroupLayout.PREFERRED_SIZE, 508, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlAdminPage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnlAdminPage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblAdminInCustodyMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblAdminInCustodyMouseClicked
        // TODO add your handling code here:
        //Set data to the respective TExtfields

        DefaultTableModel tblModel = (DefaultTableModel) tblAdminInCustody.getModel();
        // set data to text field when row is selected.
        String tblId = tblModel.getValueAt(tblAdminInCustody.getSelectedRow(), 0).toString();
        String tblName = tblModel.getValueAt(tblAdminInCustody.getSelectedRow(), 1).toString();
        String tblCrime = tblModel.getValueAt(tblAdminInCustody.getSelectedRow(), 2).toString();
        String tblSentence = tblModel.getValueAt(tblAdminInCustody.getSelectedRow(), 3).toString();

        //set to the textfield
        txtFldId.setText(tblId);
        txtFldName.setText(tblName);
        txtFldCrime.setText(tblCrime);
        txtFldSentence.setText(tblSentence);

    }//GEN-LAST:event_tblAdminInCustodyMouseClicked

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        //get table model
        DefaultTableModel tblModel = (DefaultTableModel) tblAdminInCustody.getModel();
        if (tblAdminInCustody.getSelectedRowCount() == 1) {
            // update if single row is selected
            String id = txtFldId.getText();
            String name = txtFldName.getText();
            String crime = txtFldCrime.getText();
            String sentence = txtFldSentence.getText();

            //set updated value on table
            tblModel.setValueAt(id, tblAdminInCustody.getSelectedRow(), 0);
            tblModel.setValueAt(name, tblAdminInCustody.getSelectedRow(), 1);
            tblModel.setValueAt(crime, tblAdminInCustody.getSelectedRow(), 2);
            tblModel.setValueAt(sentence, tblAdminInCustody.getSelectedRow(), 3);

            //Display Update Message
            JOptionPane.showMessageDialog(this, "updated sucessfully.");

        } else {
            if (tblAdminInCustody.getRowCount() == 0) {
                JOptionPane.showMessageDialog(this, "Please enter all the information");
            } else {
                JOptionPane.showMessageDialog(this, "Please enter all the information");
            }
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        if (txtFldId.getText().isEmpty() || txtFldName.getText().isEmpty() || txtFldCrime.getText().isEmpty() || txtFldSentence.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Please fill out all the information", "Alert", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            int Id = Integer.parseInt(txtFldId.getText());
            String Name = txtFldName.getText();
            String Crime = txtFldCrime.getText();
            String Sentence = txtFldSentence.getText();
            tableModel = (DefaultTableModel) tblAdminInCustody.getModel();
            Boolean IN = false;
            for (CriminalModel objcriminalmodel : Criminal) {
                if (objcriminalmodel.getId() == Integer.parseInt(txtFldId.getText())) {
                    IN = true;
                }
            }
            if (IN == false) {
                CriminalModel criminalinfo = new CriminalModel(Id, Name, Crime, Sentence);
                Criminal.add(criminalinfo);
                addDataToTable(criminalinfo);
            } else {
                JOptionPane.showMessageDialog(this, "same id.", "Information", JOptionPane.INFORMATION_MESSAGE);
            }

        } catch (NumberFormatException e1) {
            JOptionPane.showMessageDialog(rootPane, "Criminal Id should be a number", "Alert", JOptionPane.WARNING_MESSAGE);
        }


    }//GEN-LAST:event_btnAddActionPerformed

    private void btnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRemoveActionPerformed
        // TODO add your handling code here:

        try {
            boolean Remove = false;
            
            Iterator<CriminalModel> itr = Criminal.iterator();
            while (itr.hasNext()) {
                CriminalModel objcriminalmodel = itr.next();
                if (objcriminalmodel.getId() == Integer.parseInt(txtFldId.getText())) {
                    Remove = true;
                    itr.remove();
                    JOptionPane.showMessageDialog(this, "Criminal has been removed.", "Information", JOptionPane.INFORMATION_MESSAGE);
                    tableModel = (DefaultTableModel) tblAdminInCustody.getModel();
                    int rowCount = tblAdminInCustody.getRowCount();
                    for (int i = 0; i < rowCount; i++) {
                        if (tableModel.getValueAt(i, 0).equals(Integer.parseInt(txtFldId.getText()))) {
                            tableModel.removeRow(i);
                            break; // Exit loop after removing the row
                        }

                    }
                }
            }

            if (Remove == false) {
                JOptionPane.showMessageDialog(this, "Criminal is not in custody.", "Warning", JOptionPane.WARNING_MESSAGE);
                return;
            }
        } catch (NumberFormatException e9) {
            JOptionPane.showMessageDialog(this, "Wrong data type.", "Warning", JOptionPane.WARNING_MESSAGE);
        }

    }//GEN-LAST:event_btnRemoveActionPerformed

    private void cmbBxSortActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbBxSortActionPerformed

        // TODO add your handling code here:
        String Value = (String) cmbBxSort.getSelectedItem();

        if (Value == "Sort by Id") {
            SelectionSort selectionSort = new SelectionSort();
            Criminal = (ArrayList<CriminalModel>) selectionSort.sortByCriminalId(Criminal, false);

            // Clear and reload table
            tableModel.setRowCount(0);
            for (CriminalModel criminal : Criminal) {
                addDataToTable(criminal);
            }

        } else if (Value == "Sort by Names") {
            MergeSort selectionSort = new MergeSort();
            Criminal = (ArrayList<CriminalModel>) selectionSort.sortByName(Criminal, false);

            // Clear and reload table
            tableModel.setRowCount(0);
            for (CriminalModel criminal : Criminal) {
                addDataToTable(criminal);
            }
        }

    }//GEN-LAST:event_cmbBxSortActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        // TODO add your handling code here:
        String searchTerm = txtFldSearch.getText().trim();

        // Validate search input
        if (searchTerm.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter a name to search",
                    "Warning", JOptionPane.WARNING_MESSAGE);
            return;
        }
        // First clear any previous highlights/selections in table
        tblAdminInCustody.clearSelection();

        // Search directly in the table model
        DefaultTableModel model = (DefaultTableModel) tblAdminInCustody.getModel();
        boolean found = false;

        for (int i = 0; i < model.getRowCount(); i++) {
            String nameInTable = model.getValueAt(i, 1).toString().trim(); // Column 1 contains names

            // Case-insensitive partial match
            if (nameInTable.toLowerCase().contains(searchTerm.toLowerCase())) {
                // Select and scroll to the found row
                tblAdminInCustody.setRowSelectionInterval(i, i);
                tblAdminInCustody.scrollRectToVisible(tblAdminInCustody.getCellRect(i, 0, true));

                // Display the details in text fields
                txtFldId.setText(model.getValueAt(i, 0).toString());
                txtFldName.setText(nameInTable);
                txtFldCrime.setText(model.getValueAt(i, 2).toString());
                txtFldSentence.setText(model.getValueAt(i, 3).toString());

                found = true;
                break;  // Remove this if you want to find all matches
            }
        }

        if (!found) {
            JOptionPane.showMessageDialog(this,
                    "No criminal found with name containing: " + searchTerm,
                    "Not Found",
                    JOptionPane.INFORMATION_MESSAGE);

            // Clear the text fields if nothing is found
            txtFldId.setText("");
            txtFldName.setText("");
            txtFldCrime.setText("");
            txtFldSentence.setText("");
        }

        System.out.println("Sorry");
    }//GEN-LAST:event_btnSearchActionPerformed

    private void cmbBxSortingActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbBxSortingActionPerformed
        // TODO add your handling code here:
        String Value = (String) cmbBxSorting.getSelectedItem();

        if (Value == "Sort by Id") {

            SelectionSort selectionSort = new SelectionSort();
            MostWanted = (ArrayList<MostWantedModel>) selectionSort.sortByWantedId(MostWanted, false);

            // Clear and reload table
            tableModel1.setRowCount(0);
            for (MostWantedModel criminal : MostWanted) {
                addDataToTable1(criminal);
            }
        } //Insertion Sort
        else if (Value == "Sort by Name") {
            InsertionSort insertionSort = new InsertionSort();
            MostWanted = (ArrayList<MostWantedModel>) insertionSort.sortByName(MostWanted, false);

            // Clear and reload table
            tableModel1.setRowCount(0);
            for (MostWantedModel criminal : MostWanted) {
                addDataToTable1(criminal);
            }
        } else if (Value == "Sort by Bounty") {
            SelectionSort selectionSort = new SelectionSort();
            MostWanted = (ArrayList<MostWantedModel>) selectionSort.sortByBounty(MostWanted, false);
            // Clear and reload table
            tableModel1.setRowCount(0);
            for (MostWantedModel criminal : MostWanted) {
                addDataToTable1(criminal);
            }
        }
    }//GEN-LAST:event_cmbBxSortingActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnLoginActionPerformed

    private void txtFldQueriesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFldQueriesActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFldQueriesActionPerformed

    private void btnSendActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendActionPerformed
        // TODO add your handling code here:
        if (txtFldQueries.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Please write your querry on the given space.");
        } else {
            JOptionPane.showMessageDialog(null, "Your Querry has been sent for review.");
        }

    }//GEN-LAST:event_btnSendActionPerformed

    private void txtFldNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtFldNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFldNameActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AdminHomepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AdminHomepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AdminHomepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AdminHomepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AdminHomepage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnRemove;
    private javax.swing.JButton btnSearch;
    private javax.swing.JButton btnSend;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JComboBox<String> cmbBxSort;
    private javax.swing.JComboBox<String> cmbBxSorting;
    private javax.swing.JLabel lblBackgrounImg;
    private javax.swing.JLabel lblCrimeStats;
    private javax.swing.JLabel lblGetRapSheet;
    private javax.swing.JLabel lblHelpFind;
    private javax.swing.JLabel lblHelpWithWebsite;
    private javax.swing.JLabel lblIcon;
    private javax.swing.JLabel lblIssue;
    private javax.swing.JLabel lblLearn;
    private javax.swing.JLabel lblLeaveATip;
    private javax.swing.JLabel lblQuerriesTitle;
    private javax.swing.JLabel lblRespondACrime;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel pnlAdminContact;
    private javax.swing.JPanel pnlAdminHelp;
    private javax.swing.JPanel pnlAdminHome;
    private javax.swing.JPanel pnlAdminInCustody;
    private javax.swing.JPanel pnlAdminMWanted;
    private javax.swing.JPanel pnlAdminPage;
    private javax.swing.JPanel pnlHomeinfo;
    private javax.swing.JScrollPane scrlPaneInCustody;
    private javax.swing.JScrollPane scrlPaneMostWanted;
    private javax.swing.JTable tblAdminInCustody;
    private javax.swing.JTable tblMostWanted;
    private javax.swing.JTabbedPane tpaneAdminPage;
    private javax.swing.JTextField txtFldCrime;
    private javax.swing.JTextField txtFldId;
    private javax.swing.JTextField txtFldName;
    private javax.swing.JTextField txtFldQueries;
    private javax.swing.JTextField txtFldSearch;
    private javax.swing.JTextField txtFldSentence;
    // End of variables declaration//GEN-END:variables

}
